### PR TITLE
Enable NPM workspaces

### PR DESCRIPTION
**Pull request by kherock**
This PR enables NPM workspaces and fixes up some miscellaneous dependency problems. Most importantly, this fixes the bad npm registry in package-lock.json.

### CODE REVIEW

**Comment by pamapa** [comment]
Pipeline needs fixing, other than that look great, maybe its also good to bump nodejs to v16 in the CI

**Comment by kherock** [comment]
@pamapa I added a potential workaround for using NPM 7 with older versions of Node based on some suggestions in this thread:

https://github.com/actions/setup-node/issues/213#issuecomment-833724757

**Comment by pamapa** [comment]
@kherock lets just remove nodejs v14 support for the CI, lets keep it simple

**Review by pamapa — APPROVED** [review]

**Comment by pamapa** [comment]
great work! thanks for the contribution!

**Pull request merged**
