### PR TITLE
feature PopupWindow postmessage

### PR DESCRIPTION
**Pull request by rvdkooy**
This PR uses postmessage logic to send data back to the main window

todo:
 - [x] use postmessage
 - [x] add tests

### CODE REVIEW

**Comment by pamapa** [comment]
please fix the pipeline issues, beside of that it looks really nice!

**Comment by rvdkooy** [comment]
thanks! pipelines should be fine now after my last commits

**Comment by rvdkooy** [comment]
this one is done now and can be reviewed

**Review by pamapa — APPROVED** [review]

**Comment by pamapa** [comment]
nice work, thanks for contributing!

**Pull request merged**
